from textgenrnn import textgenrnn

"""
This file trains the KI with the text file generated by download_wagners.py.

Note that you have to manually clean up a bit, since in some articles the teaser
for other articles is included. 
"""

textgen = textgenrnn()
textgen.train_from_file("articles/wagner.txt", num_epochs=20)

